[book]
authors = ["Viliam Vadocz"]
language = "en"
multilingual = false
src = "src"
title = "Will's Website"

[output.html]
default-theme = "ayu"
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[output.html.code.hidelines]
python = "~"
